import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { CartProvider } from "./context/cartcontext";
import { AuthProvider } from "./context/authcontext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col bg-white ${geistSans.variable} ${geistMono.variable}`}
      >

      <AuthProvider>
        <CartProvider>

          <Navbar />

          <main className="flex-grow container mx-auto px-4 py-8">
            {children}
          </main>

          <Footer />

        </CartProvider>
      </AuthProvider>
      
      </body>
    </html>
  );
}